apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: traefik
spec:
  project: default

  source:
    repoURL: https://github.com/guilhermewolf/argocd-app-config.git
    targetRevision: HEAD
    path: dev/traefik
  destination: 
    server: https://kubernetes.default.svc
    namespace: traefik

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
